





  

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YXJub2xk   # base64 encoded "arnold"
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQxMjM=   # base64 encoded "password123"

